config/routes.rb
RubyShop::Application.routes.draw do

  root :to => "products#index"
  resources :products, :categories
  resources :cart, :only => :index do
    post :append_item, :remove_item, :remove_all
  end
  
  post "products_search" => "products#search"

  get "admin" => "admin#index"
  namespace :admin do 
    resources :products, :categories, :users
  end

  devise_for :users
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged

  attr_accessible :description, :name, :on_sale, :price, :qty, :sale_price,
    :category, :category_id, :photo
  belongs_to :category

  has_attached_file :photo, styles: { mini: "80x80>", thumb: "170x170>", normal: "400x400>" }

  scope :in_stock, where("qty > 0")
  scope :by_category, lambda { |id| where(category_id: id) }

  validates :name, :price, :qty, :presence => true
  validates :price, :sale_price, :qty, :numericality => true
  validates :category, :presence => true

  validates_attachment :photo,
    content_type: { content_type: /^image\/.?(gif|png|jpg|jpeg)$/i },
    size: { in: 0..2000.kilobytes }

    searchable do
      text :name
    end

  def current_price
    on_sale ? sale_price : price
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  authorize_resource  
  layout "backend"

  # GET /admin/products
  def index
    @admin_products = Product.page params[:page]

    respond_to do |format|
      format.html
      format.json { render json: @admin_products }
    end
  end

  # GET /admin/products/1
  def show
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
    @categories = get_category_list

    respond_to do |format|
      format.html
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Product.find(params[:id])
    @categories = get_category_list
  end

  # POST /admin/products
  def create
    @admin_product = Product.new(params[:product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_path(@admin_product), notice: 'Product was successfully created.' }
        format.json { render json: @admin_product, status: :created, location: @admin_product }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  def update
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      if @admin_product.update_attributes(params[:product])
        format.html { redirect_to admin_product_path(@admin_product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  def destroy
    @admin_product = Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  private
    def get_category_list
      Category.all.collect { |cat| [cat.name, cat.id] }
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :only => [:show]
  
  # GET /products
  def index
    @categories = get_all_categories
    @products = Product.in_stock.page(params[:page]).per(9)

    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def search
    search = Product.search do
      fulltext params[:name]
    end

    @categories = get_all_categories
    @products = search.results
    flash[:notice] = "No product name matched '#{params[:name]}' keywords" unless @products.any?

    render :index
  end

  private
    def get_all_categories
      Category.all
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= simple_form_for [:admin, @admin_product], :html => {:class => 'form-vertical' } do |f| %>
  <% if @admin_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
      <% @admin_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <br/>
  <%= image_tag @admin_product.photo.url(:thumb) if @admin_product.id.present? %><br/><br/>
  
  <%= f.label "Product image" %>
  <%= f.file_field :photo %>

  <%= f.input :name %>

  <%= f.label :category %>
  <%= f.select :category_id, options_for_select(@categories, @admin_product.category_id) %>

  <%= f.input :description %>
  <%= f.input :qty %>
  <%= f.input :price %>
  <%= f.input :on_sale %>
  <%= f.input :sale_price %>
  
  <%= f.button :submit %>
<% end %>

app/views/admin/products/edit.html.erb
<h2>Editing <%= @admin_product.name %> </h2>

<%= render 'form' %>

<%= link_to 'Show', @admin_product %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h3>Listing Products</h3>


<table class="table table-striped">
 <thead>
   <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Qty</th>
      <th>Price</th>
      <th>On sale</th>
      <th>Sale price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @admin_products.each do |admin_product| %>
      <tr>
        <td><%= admin_product.name %></td>
        <td><%= truncate(admin_product.description, length: 40, omission: "...") %></td>
        <td><%= admin_product.qty %></td>
        <td><%= admin_product.price %></td>
        <td><%= admin_product.on_sale %></td>
        <td><%= admin_product.sale_price %></td>
        <td>
          <%= link_to 'Show', admin_product_path(admin_product), class: "btn-small btn-info" %>
          <%= link_to 'Edit', edit_admin_product_path(admin_product), class: "btn-small btn-primary" %>
          <%= link_to 'Destroy', admin_product_path(admin_product), class: "btn-small btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<center>
<%= paginate @admin_products %>
</center>

<br />

<%= link_to 'New Product', new_admin_product_path, class: "btn" %>

app/views/admin/products/new.html.erb
<h2>New product</h2>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<%- if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end -%>

<h2>Product details</h2>
<br/>

<p>
  <%= image_tag @admin_product.photo.url(:thumb) %>
</p>

<p>
  <b>Name:</b>
  <%= @admin_product.name %>
</p>

<p>
  <b>Category:</b>
  <%= @admin_product.category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @admin_product.description %>
</p>

<p>
  <b>Qty:</b>
  <%= @admin_product.qty %>
</p>

<p>
  <b>Price:</b>
  <%= @admin_product.price %>
</p>

<p>
  <b>On sale:</b>
  <%= @admin_product.on_sale %>
</p>

<p>
  <b>Sale price:</b>
  <%= @admin_product.sale_price %>
</p>


<%= link_to 'Edit', edit_admin_product_path(@admin_product) %> |
<%= link_to 'Back', admin_products_path %>