config/routes.rb
RubyShop::Application.routes.draw do

  root :to => "products#index"
  resources :products, :categories
  resources :cart, :only => :index do
    post :append_item, :remove_item, :remove_all
  end
  
  post "products_search" => "products#search"

  get "admin" => "admin#index"
  namespace :admin do 
    resources :products, :categories, :users
  end

  devise_for :users
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged

  attr_accessible :description, :name, :on_sale, :price, :qty, :sale_price,
    :category, :category_id, :photo
  belongs_to :category

  has_attached_file :photo, styles: { mini: "80x80>", thumb: "170x170>", normal: "400x400>" }

  scope :in_stock, where("qty > 0")
  scope :by_category, lambda { |id| where(category_id: id) }

  validates :name, :price, :qty, :presence => true
  validates :price, :sale_price, :qty, :numericality => true
  validates :category, :presence => true

  validates_attachment :photo,
    content_type: { content_type: /^image\/.?(gif|png|jpg|jpeg)$/i },
    size: { in: 0..2000.kilobytes }

    searchable do
      text :name
    end

  def current_price
    on_sale ? sale_price : price
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  
  authorize_resource  
  layout "backend"

  # GET /admin/products
  def index
    @admin_products = Product.page params[:page]

    respond_to do |format|
      format.html
      format.json { render json: @admin_products }
    end
  end

  # GET /admin/products/1
  def show
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
    @categories = get_category_list

    respond_to do |format|
      format.html
      format.json { render json: @admin_product }
    end
  end

  # GET /admin/products/1/edit
  def edit
    @admin_product = Product.find(params[:id])
    @categories = get_category_list
  end

  # POST /admin/products
  def create
    @admin_product = Product.new(params[:product])

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_path(@admin_product), notice: 'Product was successfully created.' }
        format.json { render json: @admin_product, status: :created, location: @admin_product }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  def update
    @admin_product = Product.find(params[:id])

    respond_to do |format|
      if @admin_product.update_attributes(params[:product])
        format.html { redirect_to admin_product_path(@admin_product), notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  def destroy
    @admin_product = Product.find(params[:id])
    @admin_product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url }
      format.json { head :no_content }
    end
  end

  private
    def get_category_list
      Category.all.collect { |cat| [cat.name, cat.id] }
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :only => [:show]
  
  # GET /products
  def index
    @categories = get_all_categories
    @products = Product.in_stock.page(params[:page]).per(9)

    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def search
    search = Product.search do
      fulltext params[:name]
    end

    @categories = get_all_categories
    @products = search.results
    flash[:notice] = "No product name matched '#{params[:name]}' keywords" unless @products.any?

    render :index
  end

  private
    def get_all_categories
      Category.all
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/products/_products_table.html.erb
<ul class="featured-product">
  <% @products.each do |product| %>
    <li>
        <span class="product-image-wrapper">
          <%= image_tag product.photo.url(:thumb) %>
        </span>
        Name: <span class="product-name"><em><%= product.name %></em></span>
        Desc: <span class="product-name"><em><%= truncate(product.description, length: 50, omission: "...") %></em></span>
        Price: <span class="product-name"><em><%= number_to_currency product.current_price %></em></span>
        <%= link_to "SEE MORE DETAILS", product_path(product), class: "small button details" %>
        <br/>
    </li>
  <% end %>
</ul>
<center> <%= paginate @products %><br/> </center>

app/views/products/index.html.erb
<div id="featured-products">

  <h3 class="featured-products-title">Products in stock</h3>

  <div id="search">
    <%= form_tag({controller: "products", action: "search"}, method: "post") do %>
      <%= label_tag "Product name keywords" %>
      <%= text_field_tag :name, "" %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>

  <br/>

  <%= render "products/products_table" %>

</div>

app/views/products/show.html.erb
<h3>Product details for <%= @product.name %></h3>

<br/>

<p>
  <%= image_tag @product.photo.url %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Qty:</b>
  <%= @product.qty %>
</p>

<p>
  <b>On sale:</b>
  <%= @product.on_sale %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.current_price %>
</p>

<ul class="toolbar-checkout">
  <li style="float:left;"><%= link_to 'Add to Cart', cart_append_item_path(current_user.cart, product:@product), method: :post, class: "large button secondary" %></li>
  <li ><%= link_to 'Back', products_path, class: "large button secondary" %></li>
</ul>