config/routes.rb
RubyShop::Application.routes.draw do

  root :to => "products#index"
  resources :products, :categories
  resources :cart, :only => :index do
    post :append_item, :remove_item, :remove_all
  end
  
  post "products_search" => "products#search"

  get "admin" => "admin#index"
  namespace :admin do 
    resources :products, :categories, :users
  end

  devise_for :users
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyShop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!--begin header-wrapper-->
	<div id="wrap">
		<div id="header-wrapper">

	  <!--begin header-->
		<div id="header" class="clearfix">
	    
			<!--begin logo-->
			<div id="logo">
				<h1>
					<%= image_tag "ruby.png" %>
					<%= link_to "Ruby Shop", root_path %>
				</h1>
			</div>
			<!--end logo-->

			<!--begin toolbar-->
			<div id="toolbar">
				
				<%- if user_signed_in? %>
					<ul class="toolbar-checkout">
						<li>
							<%= link_to "Check Out", cart_index_path, class: "large button secondary" %>
						</li>
					</ul>
				<% end -%>
				
				<ul class="toolbar-cart">
				    <%- if user_signed_in? %>
				    	<li>Cart: <span class="toolbar-cart-count">
				    		<%= link_to "#{cart_items_count} items", cart_index_path %>
							</span>
						</li>
						<li>Hi, <%= current_user.email %> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
						</li>
					<% else %>
						<li>Hi guest, you can <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
						</li>
					<% end -%>
				</ul>
				
			</div>
			<!--end toolbar-->

			<!--begin main-navigation-->
			<div id="main-navigation">
				<ul>
					<%- get_menu_options.each do |option| %>
						<!-- class current when checked -->
						<li>
								<%= link_to "#{option}", products_path if option == 'Products' %>
								<%= link_to "#{option}", categories_path if option == 'Categories' %>
								<%= link_to "#{option}", admin_path if option == 'Admin' %>
								<%= link_to "#{option}", edit_user_registration_path if option == 'Profile' %>
								<%- if option == 'Github' %>
									<a href="http://github.com/orendon/ruby-shop"><%= option %></a>
								<% end -%>
						</li>
					<% end %>
				</ul>
			</div>
			<div style="clear: both"></div>
			<!--end main-navigation-->

	  </div>
	  <!--end header-->

	</div>
	<!--end header-wrapper-->

	<!--begin sub-banner-wrapper-->
	<div id="sub-banner-wrapper">

    	<div id="sub-banner">

			<div id="home-banner-content">
				<h2 class="title">Ruby Shop &gt;&gt;</h2>
				<!-- avoid <ul class="breadcrumb"> -->
			</div>

		</div>
  </div>
  <!--end sub-banner-wrapper-->

	<!--begin content-wrapper-->
	<div id="content-wrapper"> 

		<%- if flash.any? %>
			<div id="notice">
				<%- flash.each do |type, message| %>
					<%=  message %>
				<% end %>
				<hr/><br/>
			</div>
		<% end -%>

		<div id="left-column">
			<%= render "shared/sidebar" unless request.env['PATH_INFO'] == "/cart" %>
	  </div>

	  <div id="right-column">
    	<%= yield %>
	  </div>
		
		</div>
	</div>
	<!--end content-wrapper-->

</div>

	<!--begin footer-->
	<div id="footer">
		
		<div id="footer-content">
			
	        <div class="copyright clearfix">

	          <p>
	          	<a href="http://github.com/orendon/ruby-shop">Fork me on github</a> |

	            <%= link_to "About us", root_path %>

	            <span style="color:gray; padding:0 5px">|

	            Copyright &copy; <%= Time.now.year %> Ruby Shop.

	            <br/><br/>
	            <%= image_tag "footer-payment-methods.png" %>
	          </p>

	      	</div>
	  	</div>
	</div>

</body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "RubyShop" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "bootstrap_and_overrides.css", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to "Admin Backend", admin_path, class: "brand" %>

          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li>
                <%= link_to "RubyShop", root_path %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Menu</li>
              <li><%= link_to "Home", admin_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Admin Products", admin_products_path %></li>
              <li><%= link_to "Admin Categories", admin_categories_path %></li>
              <li><%= link_to "Admin Users", admin_users_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Back to Ruby Shop", root_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyShop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--begin header-wrapper-->
  <div id="wrap">
    <div id="header-wrapper">

    <!--begin header-->
    <div id="header" class="clearfix">
      
      <!--begin logo-->
      <div id="logo">
        <h1>
          <%= image_tag "ruby.png" %>
          <%= link_to "Ruby Shop", root_path %>
        </h1>
      </div>
      <!--end logo-->

      <!--begin toolbar-->
      <div id="toolbar">
        
        <%- if user_signed_in? %>
          <ul class="toolbar-checkout">
            <li>
              <%= link_to "Check Out", cart_index_path(user_id: current_user.id), class: "large button secondary" %>
            </li>
          </ul>
        <% end -%>
        
        <ul class="toolbar-cart">
            <%- if user_signed_in? %>
              <li>Cart: <span class="toolbar-cart-count">
                <%= link_to "#{cart_items_count} items", cart_index_path(user_id: current_user.id) %>
              </span>
            </li>
            <li>Hi, <%= current_user.email %> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li>Hi guest, you can <%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign up', new_user_registration_path %>
            </li>
          <% end -%>
        </ul>
        
      </div>
      <!--end toolbar-->

      <!--begin main-navigation-->
      <div id="main-navigation">
        <ul>
          <%- get_menu_options.each do |option| %>
            <!-- class current when checked -->
            <li>
                <%= link_to "#{option}", products_path if option == 'Products' %>
                <%= link_to "#{option}", categories_path if option == 'Categories' %>
                <%= link_to "#{option}", admin_path if option == 'Admin' %>
                <%= link_to "#{option}", edit_user_registration_path if option == 'Profile' %>
                <%= link_to "#{option}", root_path if option == 'About' %>
            </li>
          <% end %>
        </ul>
      </div>
      <div style="clear: both"></div>
      <!--end main-navigation-->

    </div>
    <!--end header-->

  </div>
  <!--end header-wrapper-->

  <!--begin sub-banner-wrapper-->
  <div id="sub-banner-wrapper">

      <div id="sub-banner">

      <div id="home-banner-content">
        <h2 class="title">Ruby Shop</h2>
        <!-- avoid <ul class="breadcrumb"> -->
      </div>

    </div>
  </div>
  <!--end sub-banner-wrapper-->

  <!--begin content-wrapper-->
  <div id="content-wrapper"> 

    <%- if flash.any? %>
      <div id="notice">
        <%- flash.each do |type, message| %>
          <%=  message %>
        <% end %>
        <hr/><br/>
      </div>
    <% end -%>

      <%= yield %>
    
    </div>
  </div>
  <!--end content-wrapper-->

</div>

  <!--begin footer-->
  <div id="footer">
    
    <div id="footer-content">
      
          <div class="copyright clearfix">

            <p>
              <%= link_to "About us", root_path %>

              <span style="color:gray; padding:0 5px">|

              Copyright &copy; <%= Time.now.year %> Ruby Shop.

              <br/><br/>
              <%= image_tag "footer-payment-methods.png" %>
            </p>

          </div>
      </div>
  </div>

</body>
</html>